### ISSUE TITLE
Streaming API

### ISSUE THREAD

**Issue by Amejame** [GreepTheSheep/discord.js-Twitter-Reposter#7]
Hi! Do you have any ideas how to do this monitor to be as fast as possible so that webhook sends message few milliseconds after the original tweet is posted? It doesn't have to be using twittter api.

**Comment by GreepTheSheep** [comment]
Hi! No, I tried, and if I reduce less than 5 seconds (time between checks), Twitter API stops working for us. I'll try to find a way to get faster...

**Comment by Amejame** [comment]
Have you thought of bypassing twitter api and maybe use scraper? For me every millisecond counts

**Comment by GreepTheSheep** [comment]
To be honest, I haven't tested with scraper. I'll test and I'll send updates here

**Comment by Amejame** [comment]
Could you give me any contact to you like discord or smth?

**Comment by GreepTheSheep** [comment]
Here, I'll send updates here ^^

**Comment by GreepTheSheep** [comment]
Anyway, all my notifications is transferred to my Discord server

**Comment by GreepTheSheep** [comment]
After a lot of searches I found a solution, using Twitter Streaming API (I tested with scraper and it won't work because of new version of Twitter)

**Comment by GreepTheSheep** [comment]
Fixed
